CREATE TABLE Users (
  UID UUID PRIMARY KEY,
  UserName CHAR(20) NOT NULL UNIQUE,
  FirstName CHAR(20) NOT NULL,
  LastName CHAR(20) NOT NULL,
  Email CHAR(50) NOT NULL,
  Password CHAR(20) NOT NULL,
  Role INTEGER NOT NULL
);

CREATE TABLE Team (
  TID UUID PRIMARY KEY,
  UID UUID NOT NULL UNIQUE,
  city CHAR(20),
  name CHAR(20) NOT NULL,
  win_rate CHAR(20),
  FOREIGN KEY (UID) REFERENCES Users
);

CREATE TABLE Player (
	PID UUID PRIMARY KEY,
  TID UUID NOT NULL,
  firstname CHAR(20),
  lastname CHAR(20),
  number INTEGER,
  FOREIGN KEY (TID) REFERENCES Team
);

CREATE TABLE Venue (
	VID UUID PRIMARY KEY,
  name CHAR(20) NOT NULL,
  city CHAR(20),
  capacity INTEGER
);

CREATE TABLE Game (
	date DATE PRIMARY KEY,
  VID UUID NOT NULL,
  sport CHAR(20) NOT NULL,
  start_time CHAR(20),
  end_time CHAR(20),
  FOREIGN KEY (VID) REFERENCES Venue
);

CREATE TABLE Manages (
  UID UUID NOT NULL,
  date DATE NOT NULL,
  PRIMARY KEY (UID, date),
  FOREIGN KEY (UID) REFERENCES Users,
  FOREIGN KEY (date) REFERENCES Game
);

CREATE TABLE Plays (
	home_TID UUID,
  away_TID UUID,
  date DATE,
  PRIMARY KEY(home_TID, away_TID, date),
  FOREIGN KEY (home_TID) REFERENCES Team(TID),
  FOREIGN KEY (away_TID) REFERENCES Team(TID),
  FOREIGN KEY (date) REFERENCES Game
);

CREATE TABLE Sponsor (
	SID UUID PRIMARY KEY,
  name CHAR(20) NOT NULL
);

CREATE TABLE Sponsors (
	SID UUID,
  date DATE,
  PRIMARY KEY(SID, date),
  FOREIGN KEY (SID) REFERENCES Sponsor,
  FOREIGN KEY (date) REFERENCES Game
);

CREATE TABLE Ticket (
	TID UUID PRIMARY KEY,
  AID UUID NOT NULL,
  cost MONEY,
  seat_num INTEGER,
  FOREIGN KEY (AID) REFERENCES Attendee
);

CREATE TABLE Attendee (
	AID UUID PRIMARY KEY,
  firstname CHAR(20),
  lastname CHAR(20)
);

CREATE TABLE TicketGame (
  TID UUID,
  date DATE,
  PRIMARY KEY(TID, date),
  FOREIGN KEY (TID) REFERENCES Team,
  FOREIGN KEY (date) REFERENCES Game
);

